/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: pac-man <pac-man@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/07 00:39:58 by pac-man           #+#    #+#             */
/*   Updated: 2021/06/09 03:18:18 by pac-man          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./includes/ft_printf.h"
#include "./includes/libft.h"

int main()
{

	// printf("===========================");
	// printf("\n");
	// printf("%x", 4294967295u);
	// printf("\n");
	// ft_printf("%x", 4294967295u);
	// printf("\n");
	// printf("===========================");
	printf("===========================");
	printf("\n");
	printf("%05x", 43);
	printf("\n");
	ft_printf("%05x", 43);
	printf("\n");
	printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("%.5d", 21);
	// printf("\n");
	// ft_printf("%.5d", 21);
	// printf("\n");
	// printf("===========================");
	// static char a01;
	// static unsigned char a02;
	// static short a03;
	// static unsigned short a04;
	// static int a05;
	// static unsigned int a06;
	// static long a07;
	// static unsigned long a08;
	// static long long a09;
	// static unsigned long long a10;
	// static char *a11;
	// static void *a12;
	// static int r00 = 0;
	// printf("===========================");
	// printf("\n");
	// ft_printf("%p", &a01);
	// printf("\n");
	// printf("%p", &a01);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("Lalalala, %d%% des gens qui parlent à Ly adorent %s. Ou Presque. %p", 100, "Ly", &r00);
	// printf("\n");
	// ft_printf("Lalalala, %d%% des gens qui parlent à Ly adorent %s. Ou Presque. %p", 100, "Ly", &r00);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// ft_printf("%p%p%p%p%p%p%p%p%p%p%p%p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// printf("\n");
	// printf("%p%p%p%p%p%p%p%p%p%p%p%p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// printf("\n");
	// printf("===========================");
	// ft_printf("%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// ft_printf("%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &a12);
	// printf("===========================");
	// printf("\n");
	// printf("%-05.7p", NULL);
	// printf("\n");
	// ft_printf("%-05.7p", NULL);
	// printf("\n");
	// printf("===========================");
	// static char *s_hidden = "hi low\0don't print me lol\0";
	//%% Tests
	// printf("===========================");
	// printf("\n");
	// printf("%%");
	// printf("\n");
	// ft_printf("%%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%5%");
	// printf("\n");
	// ft_printf("%5%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%-5%");
	// printf("\n");
	// ft_printf("%-5%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%05%");
	// printf("\n");
	// ft_printf("%05%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%-05%");
	// printf("\n");
	// ft_printf("%-05%");
	// printf("\n");
	// printf("===========================");
	// 나중에 도전!Null specifier tests
	// printf("===========================");
	// printf("\n");
	// printf("[%]");
	// printf("\n");
	// ft_printf("[%]");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%5]");
	// printf("\n");
	// // ft_printf("%5");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%05]");
	// printf("\n");
	// // ft_printf("%05");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%-05]");
	// printf("\n");
	// // ft_printf("%-05");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%-5]");
	// printf("\n");
	// // ft_printf("%-5");
	// printf("\n");
	// printf("===========================");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "hello");
	// printf("\n");
	// printf("%.s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %.*s", -1, 0);
	// printf("\n");
	// printf("printf: %.*s", -1, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %.*s", -3, 0);
	// printf("\n");
	// printf("printf: %.*s", -3, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%3.6s]", "\0");
	// printf("\n");
	// printf("-[%3.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%6.6s]", "\0");
	// printf("\n");
	// printf("-[%6.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%7.6s]", "\0");
	// printf("\n");
	// printf("-[%7.6s]", "\0");
	// printf("\n");
	// printf("========================");

	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %05d", 43);
	// printf("\n");
	// printf("printf: %05d", 43);
	// printf("\n");

	// printf("\n");
	// ft_printf("%.*s", -3, 0);
	// printf("\n");
	// printf("%.*s", -3, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.*s", -1, 0);
	// printf("\n");
	// printf("%.*s", -1, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("[%3.6s]", "\0");
	// printf("\n");
	// printf("[%3.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");

	// ft_printf("hello, %s.", "gavin");
	// printf("\n");
	// printf("hello, %s.", "gavin");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", "testing testing");
	// printf("\n");
	// printf("%s", "testing testing");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s%s", "hello", "world");
	// printf("\n");
	// printf("%s%s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("..%s stuff %s", "a", "b");
	// printf("\n");
	// printf("..%s stuff %s", "a", "b");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is empty", "");
	// printf("\n");
	// printf("this %s is empty", "");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is %s", "hello", "");
	// printf("\n");
	// printf("this %s is %s", "hello", "");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is %s", "", "hello");
	// printf("\n");
	// printf("this %s is %s", "", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s%s%s", "1", "2", "3's a charm");
	// printf("\n");
	// printf("%s%s%s", "1", "2", "3's a charm");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%32s", "abc");
	// printf("\n");
	// printf("%32s", "abc");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%16s", "nark nark");
	// printf("\n");
	// printf("%16s", "nark nark");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%5s", "goes over");
	// printf("\n");
	// printf("%5s", "goes over");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-32s", "abc");
	// printf("\n");
	// printf("%-32s", "abc");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-16s", "nark nark");
	// printf("\n");
	// printf("%-16s", "nark nark");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-5s", "goes over");
	// printf("\n");
	// printf("%-5s", "goes over");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.7s", "hello");
	// printf("\n");
	// printf("%.7s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s", "hello");
	// printf("\n");
	// printf("%.3s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "hello");
	// printf("\n");
	// printf("%.s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.0s", "hello");
	// printf("\n");
	// printf("%.0s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s%.2s", "holla", "bitch");
	// printf("\n");
	// printf("%.3s%.2s", "holla", "bitch");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.2s%.7s", "hello", "world");
	// printf("\n");
	// printf("%.2s%.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.7s%.2s", "hello", "world");
	// printf("\n");
	// printf("%.7s%.2s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.5s%7s", "yo", "boi");
	// printf("\n");
	// printf("%.5s%7s", "yo", "boi");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.5s", "yolo");
	// printf("\n");
	// printf("%7.5s", "yolo");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.5s", "bombastic");
	// printf("\n");
	// printf("%7.5s", "bombastic");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7.5s", "yolo");
	// printf("\n");
	// printf("%-7.5s", "yolo");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7.5s", "tubular");
	// printf("\n");
	// printf("%-7.5s", "tubular");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// // ft_printf("%3.7s%3.3s", "hello", "world");
	// // printf("[%3.6s]", "\0");
	// ft_printf("%.*s", -3, 0);
	// // ft_printf("%s", 0);
	// printf("\n");
	// // ft_printf("[%3.6s]", "\0");
	// // printf("%.*s", -3, NULL);
	// printf("%.*s", -3, 0);
	// // printf("%3.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3s%3s", "hello", "world");
	// printf("\n");
	// printf("%3s%3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7s%5s", "hello", "world");
	// printf("\n");
	// printf("%-7s%5s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7s%-5s", "hello", "world");
	// printf("\n");
	// printf("%7s%-5s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("hello, %s.", NULL);
	// printf("\n");
	// printf("hello, %s.", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", NULL);
	// printf("\n");
	// printf("%s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%32s", NULL);
	// printf("\n");
	// printf("%32s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%2s", NULL);
	// printf("\n");
	// printf("%2s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-32s", NULL);
	// printf("\n");
	// printf("%-32s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-16s", NULL);
	// printf("\n");
	// printf("%-16s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3s", NULL);
	// printf("\n");
	// printf("%-3s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.9s", "NULL");
	// printf("\n");
	// printf("%.9s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s", "NULL");
	// printf("\n");
	// printf("%.3s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "NULL");
	// printf("\n");
	// printf("%.s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.0s", "NULL");
	// printf("\n");
	// printf("%.0s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", s_hidden);
	// printf("\n");
	// printf("%s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3s", s_hidden);
	// printf("\n");
	// printf("%3s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9s", s_hidden);
	// printf("\n");
	// printf("%9s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", s_hidden);
	// printf("\n");
	// printf("%.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.9s", s_hidden);
	// printf("\n");
	// printf("%.9s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", s_hidden);
	// printf("\n");
	// printf("%.03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", s_hidden);
	// printf("\n");
	// printf("%.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", NULL);
	// printf("\n");
	// printf("%.03s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", NULL);
	// printf("\n");
	// printf("%.09s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.00s", "\0");
	// printf("\n");
	// printf("%.00s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.01s", "\0");
	// printf("\n");
	// printf("%.01s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", "\0");
	// printf("\n");
	// printf("%.03s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", "\0");
	// printf("\n");
	// printf("%.09s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.s", s_hidden);
	// printf("\n");
	// printf("%3.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.s", s_hidden);
	// printf("\n");
	// printf("%10.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.s", NULL);
	// printf("\n");
	// printf("%3.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.s", NULL);
	// printf("\n");
	// printf("%10.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%1.s", "\0");
	// printf("\n");
	// printf("%1.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%2.s", "\0");
	// printf("\n");
	// printf("%2.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9.s", "\0");
	// printf("\n");
	// printf("%9.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.s", s_hidden);
	// printf("\n");
	// printf("%-3.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-8.s", s_hidden);
	// printf("\n");
	// printf("%-8.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.s", NULL);
	// printf("\n");
	// printf("%-3.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-8.s", NULL);
	// printf("\n");
	// printf("%-8.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-1.s", "\0");
	// printf("\n");
	// printf("%-1.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-2.s", "\0");
	// printf("\n");
	// printf("%-2.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-6.s", "\0");
	// printf("\n");
	// printf("%-6.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.1s", s_hidden);
	// printf("\n");
	// printf("%3.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.1s", s_hidden);
	// printf("\n");
	// printf("%10.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.1s", NULL);
	// printf("\n");
	// printf("%3.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9.1s", NULL);
	// printf("\n");
	// printf("%9.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", s_hidden);
	// printf("\n");
	// printf("%-3.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.1s", s_hidden);
	// printf("\n");
	// printf("%-10.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", NULL);
	// printf("\n");
	// printf("%-3.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-9.1s", NULL);
	// printf("\n");
	// printf("%-9.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", "\0");
	// printf("\n");
	// printf("%-3.1s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-6.1s", "\0");
	// printf("\n");
	// printf("%-6.1s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", s_hidden);
	// printf("\n");
	// printf("%3.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%20.6s", s_hidden);
	// printf("\n");
	// printf("%20.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", NULL);
	// printf("\n");
	// printf("%3.6s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%20.6s", NULL);
	// printf("\n");
	// printf("%20.6s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", "\0");
	// printf("\n");
	// printf("%3.6s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%6.6s", "\0");
	// printf("\n");
	// printf("%6.6s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.6s", s_hidden);
	// printf("\n");
	// printf("%-3.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-20.6s", s_hidden);
	// printf("\n");
	// printf("%-20.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.8s", s_hidden);
	// printf("\n");
	// printf("%-3.8s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.8s", s_hidden);
	// printf("\n");
	// printf("%-10.8s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.8s", NULL);
	// printf("\n");
	// printf("%-3.8s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.8s", NULL);
	// printf("\n");
	// printf("%-10.8s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-.00s", s_hidden);
	// printf("\n");
	// printf("%-.00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-.09s", s_hidden);
	// printf("\n");
	// printf("%-.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.06s", s_hidden);
	// printf("\n");
	// printf("%+- 06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.06s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.06s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.06s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.06s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% -+06.06s", s_hidden);
	// printf("\n");
	// printf("% -+06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 07.06s", s_hidden);
	// printf("\n");
	// printf("%+- 07.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-8.06s", s_hidden);
	// printf("\n");
	// printf("% 0+-8.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-9.06s", s_hidden);
	// printf("\n");
	// printf("%0 +-9.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 10.06s", s_hidden);
	// printf("\n");
	// printf("%+-0 10.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 011.06s", s_hidden);
	// printf("\n");
	// printf("%-+ 011.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% -+012.06s", s_hidden);
	// printf("\n");
	// printf("% -+012.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.04s", s_hidden);
	// printf("\n");
	// printf("%+- 06.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.04s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.04s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.04s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.04s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0-+6.04s", s_hidden);
	// printf("\n");
	// printf("% 0-+6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.09s", s_hidden);
	// printf("\n");
	// printf("%+- 06.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.09s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.09s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.09s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.09s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0-+6.09s", s_hidden);
	// printf("\n");
	// printf("% 0-+6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%00s", s_hidden);
	// printf("\n");
	// printf("%00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%000s", s_hidden);
	// printf("\n");
	// printf("%000s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0000s", s_hidden);
	// printf("\n");
	// printf("%0000s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-00s", s_hidden);
	// printf("\n");
	// printf("%-00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0-0s", s_hidden);
	// printf("\n");
	// printf("%0-0s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%00-s", s_hidden);
	// printf("\n");
	// printf("%00-s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%03s", s_hidden);
	// printf("\n");
	// printf("%03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%09s", s_hidden);
	// printf("\n");
	// printf("%09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+03s", s_hidden);
	// printf("\n");
	// printf("%+03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+09s", s_hidden);
	// printf("\n");
	// printf("%+09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-03s", s_hidden);
	// printf("\n");
	// printf("%-03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-09s", s_hidden);
	// printf("\n");
	// printf("%-09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+ 3s", s_hidden);
	// printf("\n");
	// printf("%+ 3s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+ 6s", s_hidden);
	// printf("\n");
	// printf("%+ 6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");

	return (1);
}
