/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: taeskim <taeskim@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/07 00:39:58 by pac-man           #+#    #+#             */
/*   Updated: 2021/06/10 18:15:19 by taeskim          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./includes/ft_printf.h"
#include "./includes/libft.h"

int main()
{

	// static char a01;
	// static unsigned char a02;
	// static short a03;
	// static unsigned short a04;
	// static int a05;
	// static unsigned int a06;
	// static long a07;
	// static unsigned long a08;
	// static long long a09;
	// static unsigned long long a10;
	// static char *a11;
	// static void *a12;

	// int width;
	// int precision;

	// width = 1;
	// precision = 0;
	int		a = -4;
	int		b = 0;
	char	c = 'a';
	int		d = 2147483647;
	int		e = -2147483648;
	int		f = 42;
	int		g = 25;
	int		h = 4200;
	int		i = 8;
	int		j = -12;
	int		k = 123456789;
	int		l = 0;
	int		m = -12345678;
	char	*n = "abcdefghijklmnop";
	char	*o = "-a";
	char	*p = "-12";
	char	*q = "0";
	char	*r = "%%";
	char	*s = "-2147483648";
	char	*t = "0x12345678";
	char	*u = "-0";

	char pad = '-';

	printf("%d", ft_strlen(&pad));

	// '-'의 strlen의 0길이문제 1로 나올줄 알았는데 ft_strlen에서 2로 나옴. 원인은 모르겠음..

	// s -> segfault가 나옴..
	

	// printf("%lu", strlen(&c));
// int d = -135;

// printf("-->|%-4.*d|<--\n", -4, d);
// ft_printf("-->|%-4.*d|<--\n", -4, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", -3, d);
// ft_printf("-->|%-4.*d|<--\n", -3, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", -2, d);
// ft_printf("-->|%-4.*d|<--\n", -2, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", -1, d);
// ft_printf("-->|%-4.*d|<--\n", -1, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", 0, d);
// ft_printf("-->|%-4.*d|<--\n", 0, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", 1, d);
// ft_printf("-->|%-4.*d|<--\n", 1, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", 2, d);
// ft_printf("-->|%-4.*d|<--\n", 2, d);
// printf("===========================\n");
// printf("-->|%-4.*d|<--\n", 3, d);
// ft_printf("-->|%-4.*d|<--\n", 3, d);
// printf("===========================\n");

	// printf("===========================\n");
	// printf(" --- Return : %d\n", printf("%1s", o));
	// printf("\n");
	// printf(" --- Return : %d\n", ft_printf("%1s", o)); 
	// printf("===========================\n");

	// printf("===========================\n");
	// printf(" --- Return : %d\n", printf("%1s, %1s, %1s, %1s, %1s", n, o, p, q, r));
	// printf("\n");
	// printf(" --- Return : %d\n", ft_printf("%1s, %1s, %1s, %1s, %1s", n, o, p, q, r)); 
	// printf("===========================\n");

	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 6\n", printf("-->|%-4.*d|<--\n", 3, d));
	// printf(" --- size: 🍿%d🍿 Return : 6\n", ft_printf("-->|%-4.*d|<--\n", 3, d));
	// printf("===========================\n");
 
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 6\n", printf("|%62-+-012.-9120-+4i|", j));
	// printf(" --- size: 🍿%d🍿 Return : 6\n", ft_printf("|%62-+-012.-9120-+4i|", j));
	// printf("===========================\n");

	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 1\n", printf("%i, %d, %d, %d, %d, %s, %c, %d, %u, %x, %X", i, j, k, l, m, n, c, c, j, j, j));
	// printf(" --- size: 🍿%d🍿 Return : 1\n", ft_printf("%i, %d, %d, %d, %d, %s, %c, %d, %u, %x, %X", i, j, k, l, m, n, c, c, j, j, j));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 2\n", printf("%0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d", i, j, k, l, m, c, e, d));
	// printf(" --- size: 🍿%d🍿 Return : 2\n", ft_printf("%0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d", i, j, k, l, m, c, e, d));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 3\n", printf("%1i, %1d, %1d, %1d, %1d, %1d, %1d, %1d", i, j, k, l, m, c, e, d));
	// printf(" --- size: 🍿%d🍿 Return : 3\n", ft_printf("%1i, %1d, %1d, %1d, %1d, %1d, %1d, %1d", i, j, k, l, m, c, e, d));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 4\n", printf("%2i, %2d, %2d, %2d, %2d, %2d, %2d, %2d", i, j, k, l, m, c, e, d));
	// printf(" --- size: 🍿%d🍿 Return : 4\n", ft_printf("%2i, %2d, %2d, %2d, %2d, %2d, %2d, %2d", i, j, k, l, m, c, e, d));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 5\n", printf("%3i, %3d, %3d, %3d, %3d, %3d, %3d, %3d", i, j, k, l, m, c, e, d));
	// printf(" --- size: 🍿%d🍿 Return : 5\n", ft_printf("%3i, %3d, %3d, %3d, %3d, %3d, %3d, %3d", i, j, k, l, m, c, e, d));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 6\n", printf("|%4i|", j));
	// printf(" --- size: 🍿%d🍿 Return : 6\n", ft_printf("|%4i|", j));
	// printf("===========================\n");
	// printf(" --- size: 🍿%d🍿 Return : 7\n", printf("%5i, %5d, %5d, %5d, %5d, %5d, %5d, %5d", i, j, k, l, m, c, e, d));
	// printf(" --- size: 🍿%d🍿 Return : 7\n", ft_printf("%5i, %5d, %5d, %5d, %5d, %5d, %5d, %5d", i, j, k, l, m, c, e, d));
	// printf("===========================\n");

	// ft_printf("|%.*o|", -3, 12345);

	// printf("===========================\n");
	// printf("|%*.*p|\n", width, precision, NULL);
	// ft_printf("|%*.*p|\n", width, precision, NULL);
	// printf("===========================\n");
	// printf("|%*.*p|\n", width, precision, &a01);
	// ft_printf("|%*.*p|\n", width, precision, &a01);
	// printf("===========================\n");
	// printf("|%p|\n", &a01);
	// ft_printf("|%p|\n", &a01);
	// printf("===========================\n");
	// int d;
	// int e;
	// char *s = "abc";

	// printf("===========================\n");
	// printf("🤤%d", printf("-->|% 0*.*%|<--\n", 5, 0));
	// printf("🤤%d\n", ft_printf("-->|% 0*.*%|<--\n", 5, 0));
	// printf("===========================\n");
	// printf("-->|%+0*.*%|<--\n", 5, -5);
	// ft_printf("-->|%+0*.*%|<--\n", 5, -5);
	// printf("===========================\n");
	// printf("-->|%*.*%|<--\n", 5, 10);
	// ft_printf("-->|%*.*%|<--\n", 5, 2);
	// printf("===========================\n");
	// printf("-->|% 0*.%|<--\n", 5, 0);
	// ft_printf("-->|% 0*.%|<--\n", 5, 0);
	// printf("===========================\n");
	// printf("-->|% 0*.0%|<--\n", 5, 0);
	// ft_printf("-->|% 0*.0%|<--\n", 5, 0);
	// printf("===========================\n");
	// printf("===========================\n");
	// printf("-->|%-3.4%|<--\n");
	// ft_printf("-->|%-3.4%|<--\n");
	// printf("===========================\n");
	// d = -12;
	// e = -135;
	// printf("===========================\n");
	// printf("-->|%16.p|<--\n", &e);
	// ft_printf("-->|%16.p|<--\n", &e);
	// printf("===========================\n");
	// printf("-->|%-16p|<--\n", &e);
	// ft_printf("-->|%-16p|<--\n", &e);
	// printf("===========================\n");

	// printf("-->|%-5.6s|<--\n", s);
	// ft_printf("-->|%-5.6s|<--\n", s);
	// printf("===========================\n");
	// printf("-->|%-16.1s|<--\n", s);
	// ft_printf("-->|%-16.1s|<--\n", s);
	// printf("===========================\n");
	// printf("-->|%-6.5s|<--\n", s);
	// ft_printf("-->|%-6.5s|<--\n", s);
	// printf("===========================\n");
	// printf("-->|%-16.0s|<--\n", s);
	// ft_printf("-->|%-16.0s|<--\n", s);
	// printf("===========================\n");
	// printf("-->|%-16.s|<--\n", s);
	// ft_printf("-->|%-16.s|<--\n", s);
	// printf("===========================\n");
	// printf("-->|%-16.*s|<--\n", 0, s);
	// ft_printf("-->|%-16.*s|<--\n", 0, s);
	// printf("===========================\n");
	// printf("-->|%-5.*s|<--\n", -4, s);
	// ft_printf("-->|%-5.*s|<--\n", -4, s);
	// printf("===========================\n");
	// printf("|%-5.*s|<--\n", -2, s);
	// ft_printf("|%-5.*s|<--\n", -2, s);
	// printf("===========================\n");

	// printf("===========================\n");
	// printf("-->|%-4.0d|<--\n", 0);
	// ft_printf("-->|%-4.0d|<--\n", 0);
	// printf("===========================\n");
	// printf("-->|%-4.4d|<--\n", e);
	// ft_printf("-->|%-4.4d|<--\n", e);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, -4, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, -4, d);
	// printf("===========================\n");
	// printf("-->|%0*.d|<--\n", 4, d);
	// ft_printf("-->|%0*.d|<--\n", 4, d);
	// printf("===========================\n");
	// printf("-->|%0*.0d|<--\n", 4, d);
	// ft_printf("-->|%0*.0d|<--\n", 4, d);
	// printf("===========================\n");
	// printf("-->|%0*d|<--\n", 6, d);
	// ft_printf("-->|%0*d|<--\n", 6, d);
	// printf("===========================\n");
	// printf("-->|%0*.1d|<--\n", 4, d);
	// ft_printf("-->|%0*.1d|<--\n", 4, d);
	// printf("===========================\n");

	// printf("===========================\n");
	// printf("-->|%0*.5d|<--\n", 7, d);
	// ft_printf("-->|%0*.5d|<--\n", 7, d);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 0, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, 0, d);
	// printf("===========================\n");
	// printf("-->|%0*.d|<--\n", 10, d);
	// ft_printf("-->|%0*.d|<--\n", 10, d);
	// printf("===========================\n");
	// printf("-->|%0*d|<--\n", 10, d);
	// ft_printf("-->|%0*d|<--\n", 10, d);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 1, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, 1, d);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 2, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, 2, d);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, -2, e);
	// ft_printf("-->|%0*.*d|<--\n", 10, -2, e);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 0, e);
	// ft_printf("-->|%0*.*d|<--\n", 10, 0, e);
	// printf("===========================\n");
	// printf("-->|%0*.d|<--\n", 10, e);
	// ft_printf("-->|%0*.d|<--\n", 10, e);
	// printf("===========================\n");
	// printf("-->|%0*d|<--\n", 10, e);
	// ft_printf("-->|%0*d|<--\n", 10, e);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 1, e);
	// ft_printf("-->|%0*.*d|<--\n", 10, 1, e);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 10, 2, e);
	// ft_printf("-->|%0*.*d|<--\n", 10, 2, e);
	// printf("===========================\n");

	// printf("-->|%0*.*d|<--\n", 10, -2, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, -2, d);
	// printf("===========================\n");
	// printf("-->|%0*.*d|<--\n", 4, -4, d);
	// ft_printf("-->|%0*.*d|<--\n", 4, -4, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.*d|<--\n", 20, 2, d);
	// ft_printf("-->|%0*.*d|<--\n", 20, 2, d);
	// printf("===========================\n");
	// printf("-->|%0 *.5d|<--\n", 10, d);
	// ft_printf("-->|%0 *.5d|<--\n", 10, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.*d|<--\n", 4, -d);
	// ft_printf("-->|%-4.*d|<--\n", 4, -d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.*d|<--\n", 4, d);
	// ft_printf("-->|%-4.*d|<--\n", 4, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.d|<--\n", 4, d);
	// ft_printf("-->|%-4.d|<--\n", 4, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.0d|<--\n", 4, d);
	// ft_printf("-->|%-4.0d|<--\n", 4, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.*d|<--\n", 10, 1, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, 1, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.*d|<--\n", 10, 2, d);
	// ft_printf("-->|%0*.*d|<--\n", 10, 2, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.0d|<--\n", 4, d);
	// ft_printf("-->|%0*.0d|<--\n", 4, d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.d|<--\n", 4, d);
	// ft_printf("-->|%0*.d|<--\n", 4, d);
	// printf("===========================");

	// printf("===========================");
	// printf("\n");
	// printf("%08.5d", 34);
	// printf("\n");
	// ft_printf("%08.5d", 34);
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.*d|<--\n", 4, -135);
	// printf("\n");
	// ft_printf("-->|%-4.*d|<--\n", 4, -135);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.*d|<--\n", -4, -5, -135);
	// printf("\n");
	// ft_printf("-->|%0*.*d|<--\n", -4, -5, -135);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%*.*d|<--\n", 4, -4, -d);
	// printf("\n");
	// ft_printf("-->|%*.*d|<--\n", 4, -4, -d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.d|<--\n", -4, -d);
	// printf("\n");
	// ft_printf("-->|%0*.d|<--\n", -4, -d);
	// printf("===========================");
	// printf("\n");
	// printf("-->|%0*.4d|<--\n", 3, -d);
	// printf("\n");
	// ft_printf("-->|%0*.4d|<--\n", 3, -d);
	// printf("===========================");

	// printf("\n");
	// printf("%32s", NULL);
	// printf("\n");
	// ft_printf("%32s", NULL);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("[%7.5s]", "bombastic");
	// printf("\n");
	// ft_printf("[%7.5s]", "bombastic");
	// printf("\n")
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("[%3.1s]", NULL);
	// printf("\n");
	// ft_printf("[%3.1s]", NULL);
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%-5.d]", 0);
	// printf("\n");
	// ft_printf("[%-5.d]", 0);
	// printf("\n");
	// printf("===========================");

	// printf("===========================");
	// printf("\n");
	// printf("%x", 4294967295u);
	// printf("\n");
	// ft_printf("%x", 4294967295u);
	// printf("\n");
	// printf("===========================");

	// printf("===========================");
	// printf("\n");
	// printf("[%5.d]", 0);
	// printf("\n");
	// printf("[%5.d]", 0);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("-->|%-4.d|<--\n", d);
	// printf("\n");
	// ft_printf("-->|%-4.d|<--\n", d);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("%.5d", 21);
	// printf("\n");
	// ft_printf("%.5d", 21);
	// printf("\n");
	// printf("===========================");
	// static char a01;
	// static unsigned char a02;
	// static short a03;
	// static unsigned short a04;
	// static int a05;
	// static unsigned int a06;
	// static long a07;
	// static unsigned long a08;
	// static long long a09;
	// static unsigned long long a10;
	// static char *a11;
	// static void *ad;
	// static int r00 = 0;
	// printf("===========================");
	// printf("\n");
	// ft_printf("%p", &a01);
	// printf("\n");
	// printf("%p", &a01);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// printf("Lalalala, %d%% des gens qui parlent à Ly adorent %s. Ou Presque. %p", 100, "Ly", &r00);
	// printf("\n");
	// ft_printf("Lalalala, %d%% des gens qui parlent à Ly adorent %s. Ou Presque. %p", 100, "Ly", &r00);
	// printf("\n");
	// printf("===========================");
	// printf("===========================");
	// printf("\n");
	// ft_printf("%p%p%p%p%p%p%p%p%p%p%p%p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// printf("\n");
	// printf("%p%p%p%p%p%p%p%p%p%p%p%p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// printf("\n");
	// printf("===========================");
	// ft_printf("%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p%70p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p%5p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p%8p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p%32p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p%-70p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p%-5p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p%-16p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p%-8p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// ft_printf("%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p%-32p", &a01, &a02, &a03, &a04, &a05, &a06, &a07, &a08, &a09, &a10, &a11, &ad);
	// printf("===========================");
	// printf("\n");
	// printf("%-05.7p", NULL);
	// printf("\n");
	// ft_printf("%-05.7p", NULL);
	// printf("\n");
	// printf("===========================");
	// static char *s_hidden = "hi low\0don't print me lol\0";
	//%% Tests
	// printf("===========================");
	// printf("\n");
	// printf("%%");
	// printf("\n");
	// ft_printf("%%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%5%");
	// printf("\n");
	// ft_printf("%5%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%-5%");
	// printf("\n");
	// ft_printf("%-5%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%05%");
	// printf("\n");
	// ft_printf("%05%");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("%-05%");
	// printf("\n");
	// ft_printf("%-05%");
	// printf("\n");
	// printf("===========================");
	// 나중에 도전!Null specifier tests
	// printf("===========================");
	// printf("\n");
	// printf("[%]");
	// printf("\n");
	// ft_printf("[%]");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%5]");
	// printf("\n");
	// // ft_printf("%5");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%05]");
	// printf("\n");
	// // ft_printf("%05");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%-05]");
	// printf("\n");
	// // ft_printf("%-05");
	// printf("\n");
	// printf("===========================");
	// printf("\n");
	// printf("[%-5]");
	// printf("\n");
	// // ft_printf("%-5");
	// printf("\n");
	// printf("===========================");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "hello");
	// printf("\n");
	// printf("%.s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %.*s", -1, 0);
	// printf("\n");
	// printf("printf: %.*s", -1, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %.*s", -3, 0);
	// printf("\n");
	// printf("printf: %.*s", -3, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%3.6s]", "\0");
	// printf("\n");
	// printf("-[%3.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%6.6s]", "\0");
	// printf("\n");
	// printf("-[%6.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("+[%7.6s]", "\0");
	// printf("\n");
	// printf("-[%7.6s]", "\0");
	// printf("\n");
	// printf("========================");

	// printf("========================");
	// printf("\n");
	// ft_printf("ft_printf: %05d", 43);
	// printf("\n");
	// printf("printf: %05d", 43);
	// printf("\n");

	// printf("\n");
	// ft_printf("%.*s", -3, 0);
	// printf("\n");
	// printf("%.*s", -3, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.*s", -1, 0);
	// printf("\n");
	// printf("%.*s", -1, 0);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("[%3.6s]", "\0");
	// printf("\n");
	// printf("[%3.6s]", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");

	// printf("🤤%d", ft_printf("%-4.*s", 1, "abc"));
	// printf("\n");
	// printf("🤤%d", printf("%-4.*s", 1, "abc"));
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", "testing testing");
	// printf("\n");
	// printf("%s", "testing testing");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s%s", "hello", "world");
	// printf("\n");
	// printf("%s%s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("..%s stuff %s", "a", "b");
	// printf("\n");
	// printf("..%s stuff %s", "a", "b");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is empty", "");
	// printf("\n");
	// printf("this %s is empty", "");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is %s", "hello", "");
	// printf("\n");
	// printf("this %s is %s", "hello", "");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("this %s is %s", "", "hello");
	// printf("\n");
	// printf("this %s is %s", "", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s%s%s", "1", "2", "3's a charm");
	// printf("\n");
	// printf("%s%s%s", "1", "2", "3's a charm");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%32s", "abc");
	// printf("\n");
	// printf("%32s", "abc");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%16s", "nark nark");
	// printf("\n");
	// printf("%16s", "nark nark");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%5s", "goes over");
	// printf("\n");
	// printf("%5s", "goes over");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-32s", "abc");
	// printf("\n");
	// printf("%-32s", "abc");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-16s", "nark nark");
	// printf("\n");
	// printf("%-16s", "nark nark");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-5s", "goes over");
	// printf("\n");
	// printf("%-5s", "goes over");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.7s", "hello");
	// printf("\n");
	// printf("%.7s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s", "hello");
	// printf("\n");
	// printf("%.3s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "hello");
	// printf("\n");
	// printf("%.s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.0s", "hello");
	// printf("\n");
	// printf("%.0s", "hello");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s%.2s", "holla", "bitch");
	// printf("\n");
	// printf("%.3s%.2s", "holla", "bitch");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.2s%.7s", "hello", "world");
	// printf("\n");
	// printf("%.2s%.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.7s%.2s", "hello", "world");
	// printf("\n");
	// printf("%.7s%.2s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.5s%7s", "yo", "boi");
	// printf("\n");
	// printf("%.5s%7s", "yo", "boi");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.5s", "yolo");
	// printf("\n");
	// printf("%7.5s", "yolo");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.5s", "bombastic");
	// printf("\n");
	// printf("%7.5s", "bombastic");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7.5s", "yolo");
	// printf("\n");
	// printf("%-7.5s", "yolo");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7.5s", "tubular");
	// printf("\n");
	// printf("%-7.5s", "tubular");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%7.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%3.7s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%3.7s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%7.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// // ft_printf("%3.7s%3.3s", "hello", "world");
	// // printf("[%3.6s]", "\0");
	// ft_printf("%.*s", -3, 0);
	// // ft_printf("%s", 0);
	// printf("\n");
	// // ft_printf("[%3.6s]", "\0");
	// // printf("%.*s", -3, NULL);
	// printf("%.*s", -3, 0);
	// // printf("%3.7s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%7.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%7.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("%3.3s%3.3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3s%3s", "hello", "world");
	// printf("\n");
	// printf("%3s%3s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-7s%5s", "hello", "world");
	// printf("\n");
	// printf("%-7s%5s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%7s%-5s", "hello", "world");
	// printf("\n");
	// printf("%7s%-5s", "hello", "world");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("hello, %s.", NULL);
	// printf("\n");
	// printf("hello, %s.", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", NULL);
	// printf("\n");
	// printf("%s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%32s", NULL);
	// printf("\n");
	// printf("%32s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%2s", NULL);
	// printf("\n");
	// printf("%2s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-32s", NULL);
	// printf("\n");
	// printf("%-32s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-16s", NULL);
	// printf("\n");
	// printf("%-16s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3s", NULL);
	// printf("\n");
	// printf("%-3s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.9s", "NULL");
	// printf("\n");
	// printf("%.9s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.3s", "NULL");
	// printf("\n");
	// printf("%.3s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", "NULL");
	// printf("\n");
	// printf("%.s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.0s", "NULL");
	// printf("\n");
	// printf("%.0s", "NULL");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%s", s_hidden);
	// printf("\n");
	// printf("%s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3s", s_hidden);
	// printf("\n");
	// printf("%3s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9s", s_hidden);
	// printf("\n");
	// printf("%9s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.s", s_hidden);
	// printf("\n");
	// printf("%.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.9s", s_hidden);
	// printf("\n");
	// printf("%.9s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", s_hidden);
	// printf("\n");
	// printf("%.03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", s_hidden);
	// printf("\n");
	// printf("%.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", NULL);
	// printf("\n");
	// printf("%.03s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", NULL);
	// printf("\n");
	// printf("%.09s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.00s", "\0");
	// printf("\n");
	// printf("%.00s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.01s", "\0");
	// printf("\n");
	// printf("%.01s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.03s", "\0");
	// printf("\n");
	// printf("%.03s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%.09s", "\0");
	// printf("\n");
	// printf("%.09s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.s", s_hidden);
	// printf("\n");
	// printf("%3.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.s", s_hidden);
	// printf("\n");
	// printf("%10.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.s", NULL);
	// printf("\n");
	// printf("%3.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.s", NULL);
	// printf("\n");
	// printf("%10.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%1.s", "\0");
	// printf("\n");
	// printf("%1.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%2.s", "\0");
	// printf("\n");
	// printf("%2.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9.s", "\0");
	// printf("\n");
	// printf("%9.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.s", s_hidden);
	// printf("\n");
	// printf("%-3.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-8.s", s_hidden);
	// printf("\n");
	// printf("%-8.s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.s", NULL);
	// printf("\n");
	// printf("%-3.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-8.s", NULL);
	// printf("\n");
	// printf("%-8.s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-1.s", "\0");
	// printf("\n");
	// printf("%-1.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-2.s", "\0");
	// printf("\n");
	// printf("%-2.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-6.s", "\0");
	// printf("\n");
	// printf("%-6.s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.1s", s_hidden);
	// printf("\n");
	// printf("%3.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%10.1s", s_hidden);
	// printf("\n");
	// printf("%10.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.1s", NULL);
	// printf("\n");
	// printf("%3.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%9.1s", NULL);
	// printf("\n");
	// printf("%9.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", s_hidden);
	// printf("\n");
	// printf("%-3.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.1s", s_hidden);
	// printf("\n");
	// printf("%-10.1s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", NULL);
	// printf("\n");
	// printf("%-3.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-9.1s", NULL);
	// printf("\n");
	// printf("%-9.1s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.1s", "\0");
	// printf("\n");
	// printf("%-3.1s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-6.1s", "\0");
	// printf("\n");
	// printf("%-6.1s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", s_hidden);
	// printf("\n");
	// printf("%3.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%20.6s", s_hidden);
	// printf("\n");
	// printf("%20.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", NULL);
	// printf("\n");
	// printf("%3.6s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%20.6s", NULL);
	// printf("\n");
	// printf("%20.6s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%3.6s", "\0");
	// printf("\n");
	// printf("%3.6s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%6.6s", "\0");
	// printf("\n");
	// printf("%6.6s", "\0");
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.6s", s_hidden);
	// printf("\n");
	// printf("%-3.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-20.6s", s_hidden);
	// printf("\n");
	// printf("%-20.6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.8s", s_hidden);
	// printf("\n");
	// printf("%-3.8s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.8s", s_hidden);
	// printf("\n");
	// printf("%-10.8s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-3.8s", NULL);
	// printf("\n");
	// printf("%-3.8s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-10.8s", NULL);
	// printf("\n");
	// printf("%-10.8s", NULL);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-.00s", s_hidden);
	// printf("\n");
	// printf("%-.00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-.09s", s_hidden);
	// printf("\n");
	// printf("%-.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.06s", s_hidden);
	// printf("\n");
	// printf("%+- 06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.06s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.06s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.06s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.06s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% -+06.06s", s_hidden);
	// printf("\n");
	// printf("% -+06.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 07.06s", s_hidden);
	// printf("\n");
	// printf("%+- 07.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-8.06s", s_hidden);
	// printf("\n");
	// printf("% 0+-8.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-9.06s", s_hidden);
	// printf("\n");
	// printf("%0 +-9.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 10.06s", s_hidden);
	// printf("\n");
	// printf("%+-0 10.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 011.06s", s_hidden);
	// printf("\n");
	// printf("%-+ 011.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% -+0d.06s", s_hidden);
	// printf("\n");
	// printf("% -+0d.06s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.04s", s_hidden);
	// printf("\n");
	// printf("%+- 06.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.04s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.04s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.04s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.04s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0-+6.04s", s_hidden);
	// printf("\n");
	// printf("% 0-+6.04s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+- 06.09s", s_hidden);
	// printf("\n");
	// printf("%+- 06.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0+-6.09s", s_hidden);
	// printf("\n");
	// printf("% 0+-6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0 +-6.09s", s_hidden);
	// printf("\n");
	// printf("%0 +-6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+-0 6.09s", s_hidden);
	// printf("\n");
	// printf("%+-0 6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-+ 06.09s", s_hidden);
	// printf("\n");
	// printf("%-+ 06.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("% 0-+6.09s", s_hidden);
	// printf("\n");
	// printf("% 0-+6.09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%00s", s_hidden);
	// printf("\n");
	// printf("%00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%000s", s_hidden);
	// printf("\n");
	// printf("%000s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0000s", s_hidden);
	// printf("\n");
	// printf("%0000s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-00s", s_hidden);
	// printf("\n");
	// printf("%-00s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%0-0s", s_hidden);
	// printf("\n");
	// printf("%0-0s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%00-s", s_hidden);
	// printf("\n");
	// printf("%00-s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%03s", s_hidden);
	// printf("\n");
	// printf("%03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%09s", s_hidden);
	// printf("\n");
	// printf("%09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+03s", s_hidden);
	// printf("\n");
	// printf("%+03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+09s", s_hidden);
	// printf("\n");
	// printf("%+09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-03s", s_hidden);
	// printf("\n");
	// printf("%-03s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%-09s", s_hidden);
	// printf("\n");
	// printf("%-09s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+ 3s", s_hidden);
	// printf("\n");
	// printf("%+ 3s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");
	// ft_printf("%+ 6s", s_hidden);
	// printf("\n");
	// printf("%+ 6s", s_hidden);
	// printf("\n");
	// printf("========================");
	// printf("\n");

	return (1);
}
